# Generated by Django 6.0 on 2025-12-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lock_In_API_REST', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
