# Generated by Django 6.0 on 2025-12-24 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lock_In_API_REST', '0002_objetivo_completado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField(max_length=200)),
                ('etiqueta', models.CharField(choices=[('Logros', 'Logro'), ('Ayuda', 'Ayuda'), ('Motivación', 'Motivacion')], max_length=10)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Corazones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corazon', models.BooleanField(default=False)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Lock_In_API_REST.post')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id_autor', 'id_post'), name='unique_autor_post_relacion')],
            },
        ),
        migrations.CreateModel(
            name='SesionEnfoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_totales', models.IntegerField()),
                ('minutos_segundo_plano', models.IntegerField()),
                ('id_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lock_In_API_REST.objetivo')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('minutos_totales__gte', models.F('minutos_segundo_plano'))), name='totales_gte_segundo_plano')],
            },
        ),
    ]
